-- SQL schema for Project1 User Manager
CREATE DATABASE IF NOT EXISTS project1 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE project1;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS tokens (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  token VARCHAR(255) NOT NULL,
  expires_at DATETIME NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX (token),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
